import { z } from "zod";


export const RadnikSchema = z.object({
    radBr: z.string().length(6, "Polje može imati maksimalno 6 karaktera.").min(1, "Obavezno"),
    organizacionaJedinica: z.string().length(12, "Polje može imati maksimalno 12 karaktera.").optional(),
    preizme: z.string().length(100, "Polje može imati maksimalno 100 karaktera.").min(1, "Obavezno"),
    ime: z.string().length(100, "Polje može imati maksimalno 100 karaktera.").min(1, "Obavezno"),
    srSlovo: z.string().length(2, "Polje može imati maksimalno 2 karaktera.").optional(),
    roditelj: z.string().length(20, "Polje može imati maksimalno 20 karaktera.").optional(),
    devPrez: z.string().length(20, "Polje može imati maksimalno 20 karaktera.").optional(),
    datRodj: z.date().optional(),
    pol: z.string().length(1, "Polje može imati maksimalno 1 karaktera.").min(1, "Obavezno"),
    licniBr: z.string().length(13, "Polje može imati maksimalno 13 karaktera.").optional(),
    opsrBr: z.string().length(5, "Polje može imati maksimalno 5 karaktera.").optional(),
    opsBr: z.string().length(5, "Polje može imati maksimalno 5 karaktera.").min(1, "Obavezno"),
    mzBr: z.string().length(4, "Polje može imati maksimalno 4 karaktera.").min(1, "Obavezno"),
    adresa: z.string().length(40, "Polje može imati maksimalno 40 karaktera.").optional(),
    telefon: z.string().length(30, "Polje može imati maksimalno 30 karaktera.").optional(),
    statusBr: z.string().length(1, "Polje može imati maksimalno 1 karaktera.").min(1, "Obavezno"),
    spremaBr: z.string().length(3, "Polje može imati maksimalno 3 karaktera.").min(1, "Obavezno"),
    veraBr: z.string().length(3, "Polje može imati maksimalno 3 karaktera.").optional(),
    nacBr: z.string().length(3, "Polje može imati maksimalno 3 karaktera.").optional(),
    slavaBr: z.string().length(3, "Polje može imati maksimalno 3 karaktera.").optional(),
    datumDol: z.date().optional(),
    datumOdl: z.date().optional(),
    bracnoStanje: z.string().length(1, "Polje može imati maksimalno 1 karaktera.").optional(),
    slika: z.string().length(6, "Polje može imati maksimalno 6 karaktera.").optional(),
    zastareo: z.string().length(1, "Polje može imati maksimalno 1 karaktera.").optional(),
    datum: z.date(),
    radBrRef: z.string().length(6, "Polje može imati maksimalno 6 karaktera.").optional(),
    spremaBrInt: z.string().length(3, "Polje može imati maksimalno 3 karaktera.").optional(),
    opsBrRada: z.string().length(5, "Polje može imati maksimalno 5 karaktera.").optional(),
    username: z.string().length(30, "Polje može imati maksimalno 30 karaktera.").optional(),
    nadzor: z.number().optional(),
    obrJedinica: z.string().length(12, "Polje može imati maksimalno 12 karaktera.").optional(),
    stevBr: z.string().length(6, "Polje može imati maksimalno 6 karaktera.").optional(),
    sortniPojam: z.string().length(50, "Polje može imati maksimalno 50 karaktera.").optional(),
    samohran: z.string().length(1, "Polje može imati maksimalno 1 karaktera.").optional(),
    titula: z.string().length(10, "Polje može imati maksimalno 10 karaktera.").optional(),
    lbo: z.string().length(11, "Polje može imati maksimalno 11 karaktera.").optional(),
    mail: z.string().length(255, "Polje može imati maksimalno 255 karaktera.").optional(),
    externalUsername: z.string().length(255, "Polje može imati maksimalno 255 karaktera.").optional(),
    jeStranac: z.string().length(1, "Polje može imati maksimalno 1 karaktera.").optional(),
    brojLk: z.string().length(50, "Polje može imati maksimalno 50 karaktera.").optional(),
});


export type Radnik = z.infer<typeof RadnikSchema>;